services:

  api:
    build: .
    container_name: go-gin-todos-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: todos-db
    environment:
      POSTGRES_USER: user-todos
      POSTGRES_PASSWORD: pass-todos
      POSTGRES_DB: db-todos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
