
name: Go CI for Todo App

on:
  push:
    branches: [ "main" ] 
    paths:
      - 'go-gin-todos/**' 

  pull_request:
    branches: [ "main" ] 
    paths:
      - 'go-gin-todos/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' 

      - name: Download Dependencies
        run: go mod download
        
        working-directory: ./go-gin-todos

      - name: Run Tests
        run: go test ./...
        working-directory: ./go-gin-todos

      - name: Build Application
        run: go build -v ./cmd/api
        working-directory: ./go-gin-todos